/**:
  ros__parameters:
    chassis_base_frame: coupling_b3a85bca56_base
    extension_metric: horizontal_reach
    input_topic: /coupling_b3a85bca56/input
    joint_states_topic: /coupling_b3a85bca56/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_b3a85bca56_reach
    output_topic: /coupling_b3a85bca56/python/output
    use_sim_time: false
