/**:
  ros__parameters:
    chassis_base_frame: coupling_cb994b7a60_base
    extension_metric: horizontal_reach
    input_topic: /coupling_cb994b7a60/input
    joint_states_topic: /coupling_cb994b7a60/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_cb994b7a60_reach
    output_topic: /coupling_cb994b7a60/cpp/output
    reach_update_period_sec: 0.0
    scale_smoothing_alpha: 1.0
    use_sim_time: true
