/**:
  ros__parameters:
    chassis_base_frame: coupling_71b478bed4_base
    extension_metric: joint_deviation
    input_topic: /coupling_71b478bed4/input
    joint_states_topic: /coupling_71b478bed4/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_71b478bed4_reach
    output_topic: /coupling_71b478bed4/python/output
    use_sim_time: true
