/**:
  ros__parameters:
    chassis_base_frame: coupling_dc6f105db5_base
    extension_metric: horizontal_reach
    input_topic: /coupling_dc6f105db5/input
    joint_states_topic: /coupling_dc6f105db5/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_dc6f105db5_reach
    output_topic: /coupling_dc6f105db5/python/output
    use_sim_time: false
