/**:
  ros__parameters:
    chassis_base_frame: coupling_803a652335_base
    extension_metric: invalid
    input_topic: /coupling_803a652335/input
    joint_states_topic: /coupling_803a652335/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_803a652335_reach
    output_topic: /coupling_803a652335/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
