/**:
  ros__parameters:
    chassis_base_frame: coupling_c995cc732b_base
    extension_metric: joint_deviation
    input_topic: /coupling_c995cc732b/input
    joint_states_topic: /coupling_c995cc732b/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_c995cc732b_reach
    output_topic: /coupling_c995cc732b/python/output
    use_sim_time: true
