string internal_id
string user_id
string operation
string[] parts_to_acquire
string[] parts_to_release
bool force
---
bool success
string message
string[] acquired_parts
string[] released_parts
string[] failed_parts
string[] conflicted_parts
string[] conflicted_internal_ids
string[] conflicted_user_ids
ControlPartStatus[] parts_status
