/**:
  ros__parameters:
    chassis_base_frame: coupling_389ae79cc6_base
    extension_metric: horizontal_reach
    input_topic: /coupling_389ae79cc6/input
    joint_states_topic: /coupling_389ae79cc6/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_389ae79cc6_reach
    output_topic: /coupling_389ae79cc6/cpp/output
    use_sim_time: false
