/**:
  ros__parameters:
    chassis_base_frame: coupling_8192b456ba_base
    extension_metric: horizontal_reach
    input_topic: /coupling_8192b456ba/input
    joint_states_topic: /coupling_8192b456ba/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_8192b456ba_reach
    output_topic: /coupling_8192b456ba/python/output
    use_sim_time: false
