/**:
  ros__parameters:
    chassis_base_frame: coupling_213da31680_base
    extension_metric: horizontal_reach
    input_topic: /coupling_213da31680/input
    joint_states_topic: /coupling_213da31680/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_213da31680_reach
    output_topic: /coupling_213da31680/python/output
    reach_full_m: 0.42
    scale_smoothing_alpha: 1.0
    use_sim_time: true
