/**:
  ros__parameters:
    chassis_base_frame: coupling_874ee1a462_base
    extension_metric: joint_deviation
    input_topic: /coupling_874ee1a462/input
    joint_states_topic: /coupling_874ee1a462/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_874ee1a462_reach
    output_topic: /coupling_874ee1a462/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
