find_package(astribot_s1_robot_geometry REQUIRED)
find_package(OpenSSL REQUIRED)
add_library(fixed_envelope_core STATIC src/fixed_envelope_core.cpp)
target_include_directories(fixed_envelope_core PUBLIC include)
target_link_libraries(fixed_envelope_core PUBLIC nlohmann_json::nlohmann_json OpenSSL::Crypto)
target_compile_options(fixed_envelope_core PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(fixed_envelope_core PUBLIC astribot_navigation_msgs astribot_s1_robot_geometry)
add_executable(fixed_envelope_cpp src/fixed_envelope_node.cpp)
target_link_libraries(fixed_envelope_cpp fixed_envelope_core policy_profile)
target_compile_options(fixed_envelope_cpp PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(fixed_envelope_cpp rclcpp nav_msgs ament_index_cpp)
install(TARGETS fixed_envelope_cpp RUNTIME DESTINATION lib/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_gtest REQUIRED)
  find_package(astribot_s1_transport_native REQUIRED)
  find_package(astribot_s1_payload_state REQUIRED)
  ament_add_gtest(fixed_hold_flow_test test/fixed_hold_flow_test.cpp)
  target_link_libraries(fixed_hold_flow_test fixed_envelope_core policy_profile astribot_s1_transport_native::arm_hold_core astribot_s1_payload_state::payload_state_core)
  target_compile_definitions(fixed_hold_flow_test PRIVATE PROFILE_FILE="${CMAKE_CURRENT_SOURCE_DIR}/../astribot_s1_navigation_policy/config/simulation.json")
  add_executable(fixed_envelope_probe test/fixed_envelope_probe.cpp)
  target_link_libraries(fixed_envelope_probe fixed_envelope_core policy_profile)
  add_executable(fixed_envelope_core_test test/fixed_envelope_core_test.cpp)
  target_link_libraries(fixed_envelope_core_test fixed_envelope_core policy_profile)
  target_compile_options(fixed_envelope_core_test PRIVATE -UNDEBUG)
  add_test(NAME fixed_envelope_authority COMMAND fixed_envelope_core_test
    "${CMAKE_CURRENT_SOURCE_DIR}/../astribot_s1_navigation_policy/config/simulation.json")
endif()
