/**:
  ros__parameters:
    chassis_base_frame: coupling_d98655bda6_base
    extension_metric: horizontal_reach
    input_topic: /coupling_d98655bda6/input
    joint_states_topic: /coupling_d98655bda6/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_d98655bda6_reach
    output_topic: /coupling_d98655bda6/python/output
    reach_update_period_sec: 0.1
    scale_smoothing_alpha: 1.0
    use_sim_time: true
