/**:
  ros__parameters:
    chassis_base_frame: coupling_5ac87d33a3_base
    extension_metric: joint_deviation
    input_topic: /coupling_5ac87d33a3/input
    joint_states_topic: /coupling_5ac87d33a3/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_5ac87d33a3_reach
    output_topic: /coupling_5ac87d33a3/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
