/**:
  ros__parameters:
    chassis_base_frame: coupling_e0c78070b4_base
    extension_metric: joint_deviation
    input_topic: /coupling_e0c78070b4/input
    joint_states_topic: /coupling_e0c78070b4/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_e0c78070b4_reach
    output_topic: /coupling_e0c78070b4/python/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
