/**:
  ros__parameters:
    chassis_base_frame: coupling_6d3921fdba_base
    extension_metric: invalid
    input_topic: /coupling_6d3921fdba/input
    joint_states_topic: /coupling_6d3921fdba/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_6d3921fdba_reach
    output_topic: /coupling_6d3921fdba/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
