# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DFASTCDR_DYN_LINK -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -DRCUTILS_ENABLE_FAULT_INJECTION

CXX_INCLUDES = -I/home/yjh/WorkSpace/astribot_sdk_ros2/ws_robot/src/astribot_s1_navigation_policy_native/include -isystem /home/yjh/WorkSpace/astribot_sdk_ros2/ws_robot/install/astribot_navigation_msgs/include/astribot_navigation_msgs -isystem /tmp/codex_geometry_cpp_20260921/install-no-compat/astribot_s1_robot_geometry/include -isystem /opt/ros/humble/include/builtin_interfaces -isystem /opt/ros/humble/include/rosidl_runtime_c -isystem /opt/ros/humble/include/rcutils -isystem /opt/ros/humble/include/rosidl_typesupport_interface -isystem /opt/ros/humble/include/geometry_msgs -isystem /opt/ros/humble/include/std_msgs -isystem /opt/ros/humble/include/nav_msgs -isystem /opt/ros/humble/include/sensor_msgs -isystem /opt/ros/humble/include/trajectory_msgs -isystem /opt/ros/humble/include/fastcdr -isystem /opt/ros/humble/include/rosidl_runtime_cpp -isystem /opt/ros/humble/include/rosidl_typesupport_fastrtps_cpp -isystem /opt/ros/humble/include/rmw -isystem /opt/ros/humble/include/rosidl_typesupport_fastrtps_c -isystem /opt/ros/humble/include/rosidl_typesupport_introspection_c -isystem /opt/ros/humble/include/rosidl_typesupport_introspection_cpp -isystem /home/yjh/WorkSpace/astribot_sdk_ros2/ws_robot/install/astribot_eigen_vendor/include/eigen3

CXX_FLAGS = -O3 -DNDEBUG -fPIC -Wall -Wextra -Wpedantic -std=gnu++17

