/**:
  ros__parameters:
    chassis_base_frame: coupling_043a4d1c21_base
    extension_metric: joint_deviation
    input_topic: /coupling_043a4d1c21/input
    joint_states_topic: /coupling_043a4d1c21/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_043a4d1c21_reach
    output_topic: /coupling_043a4d1c21/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
