/**:
  ros__parameters:
    chassis_base_frame: coupling_3acbe39d0c_base
    extension_metric: invalid
    input_topic: /coupling_3acbe39d0c/input
    joint_states_topic: /coupling_3acbe39d0c/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_3acbe39d0c_reach
    output_topic: /coupling_3acbe39d0c/python/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
