hunav_loader:
  ros__parameters:
    yaml_base_name: h2_empty_observed
    simulator: Gazebo Fortress
    map: small_warehouse
    publish_people: false
    global_goals: {}
    agents: []
    wait_for_episode_start: true
    enable_empty_observations: true
