/**:
  ros__parameters:
    chassis_base_frame: coupling_f586ec1d4e_base
    extension_metric: horizontal_reach
    input_topic: /coupling_f586ec1d4e/input
    joint_states_topic: /coupling_f586ec1d4e/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_f586ec1d4e_reach
    output_topic: /coupling_f586ec1d4e/python/output
    reach_update_period_sec: 0.1
    scale_smoothing_alpha: 1.0
    use_sim_time: true
