# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/codex_geometry_validation_20260921/baseline_src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/codex_geometry_validation_20260921/baseline_build

# Include any dependencies generated for this target.
include CMakeFiles/_geometry_native.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/_geometry_native.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/_geometry_native.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/_geometry_native.dir/flags.make

CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o: CMakeFiles/_geometry_native.dir/flags.make
CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o: /tmp/codex_geometry_validation_20260921/baseline_src/src/geometry_native.cpp
CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o: CMakeFiles/_geometry_native.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/tmp/codex_geometry_validation_20260921/baseline_build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o -MF CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o.d -o CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o -c /tmp/codex_geometry_validation_20260921/baseline_src/src/geometry_native.cpp

CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /tmp/codex_geometry_validation_20260921/baseline_src/src/geometry_native.cpp > CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.i

CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /tmp/codex_geometry_validation_20260921/baseline_src/src/geometry_native.cpp -o CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.s

# Object files for target _geometry_native
_geometry_native_OBJECTS = \
"CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o"

# External object files for target _geometry_native
_geometry_native_EXTERNAL_OBJECTS =

_geometry_native.cpython-310-x86_64-linux-gnu.so: CMakeFiles/_geometry_native.dir/src/geometry_native.cpp.o
_geometry_native.cpython-310-x86_64-linux-gnu.so: CMakeFiles/_geometry_native.dir/build.make
_geometry_native.cpython-310-x86_64-linux-gnu.so: /usr/lib/x86_64-linux-gnu/libcrypto.so
_geometry_native.cpython-310-x86_64-linux-gnu.so: /usr/lib/x86_64-linux-gnu/libtinyxml2.so
_geometry_native.cpython-310-x86_64-linux-gnu.so: CMakeFiles/_geometry_native.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/tmp/codex_geometry_validation_20260921/baseline_build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX shared module _geometry_native.cpython-310-x86_64-linux-gnu.so"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/_geometry_native.dir/link.txt --verbose=$(VERBOSE)
	/usr/bin/strip /tmp/codex_geometry_validation_20260921/baseline_build/_geometry_native.cpython-310-x86_64-linux-gnu.so

# Rule to build all files generated by this target.
CMakeFiles/_geometry_native.dir/build: _geometry_native.cpython-310-x86_64-linux-gnu.so
.PHONY : CMakeFiles/_geometry_native.dir/build

CMakeFiles/_geometry_native.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/_geometry_native.dir/cmake_clean.cmake
.PHONY : CMakeFiles/_geometry_native.dir/clean

CMakeFiles/_geometry_native.dir/depend:
	cd /tmp/codex_geometry_validation_20260921/baseline_build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /tmp/codex_geometry_validation_20260921/baseline_src /tmp/codex_geometry_validation_20260921/baseline_src /tmp/codex_geometry_validation_20260921/baseline_build /tmp/codex_geometry_validation_20260921/baseline_build /tmp/codex_geometry_validation_20260921/baseline_build/CMakeFiles/_geometry_native.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/_geometry_native.dir/depend

