# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -D_geometry_native_EXPORTS

CXX_INCLUDES = -I/tmp/codex_geometry_validation_20260921/baseline_src/include -isystem /usr/include/python3.10 -isystem /home/yjh/WorkSpace/astribot_sdk_ros2/ws_robot/install/astribot_eigen_vendor/include/eigen3

CXX_FLAGS = -O3 -DNDEBUG -fPIC -fvisibility=hidden -Wall -Wextra -Wpedantic -flto -fno-fat-lto-objects

