# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I/home/yjh/WorkSpace/astribot_sdk_ros2/ws_robot/src/astribot_s1_chassis_effort_drive_native/include

CXX_FLAGS = -O3 -DNDEBUG -Wall -Wextra -Wpedantic -UNDEBUG

