/**:
  ros__parameters:
    chassis_base_frame: coupling_17e6496d9b_base
    extension_metric: joint_deviation
    input_topic: /coupling_17e6496d9b/input
    joint_states_topic: /coupling_17e6496d9b/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_17e6496d9b_reach
    output_topic: /coupling_17e6496d9b/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
