/**:
  ros__parameters:
    chassis_base_frame: coupling_6932e125dc_base
    extension_metric: joint_deviation
    input_topic: /coupling_6932e125dc/input
    joint_states_topic: /coupling_6932e125dc/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_6932e125dc_reach
    output_topic: /coupling_6932e125dc/python/output
    use_sim_time: true
