/**:
  ros__parameters:
    chassis_base_frame: coupling_9ec5f0baff_base
    extension_metric: horizontal_reach
    input_topic: /coupling_9ec5f0baff/input
    joint_states_topic: /coupling_9ec5f0baff/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_9ec5f0baff_reach
    output_topic: /coupling_9ec5f0baff/cpp/output
    use_sim_time: false
