
livox_mid360_left:
  parent_frame: astribot_torso_base
  mount_position: 左前（= lidar_front，IP 192.168.0.12，标定基准）
  xyz: [0.17393, 0.16893, 0.082]
  rpy: [0.0, 0.0, -0.800058]

livox_mid360_right:
  parent_frame: astribot_torso_base
  mount_position: 右后（= lidar_back，IP 192.168.0.13）
  xyz: [-0.18120, -0.17733, 0.166]
  rpy: [0.001168, -0.009370, 2.373036]
