
/livox_preprocess_left:
  ros__parameters:
    range_min: 0.35
    range_max: 35.0
    ground_z_min: -0.1620
    height_max: 3.0
    voxel_size: 0.15
    min_points_per_voxel: 2

/livox_preprocess_right:
  ros__parameters:
    range_min: 0.35
    range_max: 35.0
    ground_z_min: -0.2460
    height_max: 3.0
    voxel_size: 0.15
    min_points_per_voxel: 2

