
/**:
  ros__parameters:
    source_map_topic: "/slam/map"

    source_map_qos: "auto"

    source_map_frame: "map"

    map_topic: "/map"
    map_frame: "map"
    odom_frame: "odom"

    republish_period_sec: 5.0

    strict_contract: true

    source_timeout_sec: 30.0

    resolution_expected: 0.05

    strict_cell_values: true

    report_period_sec: 10.0

slam_adapter:
  ros__parameters:
    source_map_topic: "/slam/map"
    source_map_qos: "auto"
    republish_period_sec: 5.0
    strict_contract: true
    source_timeout_sec: 30.0
