/**:
  ros__parameters:
    chassis_base_frame: coupling_1502829dee_base
    extension_metric: joint_deviation
    input_topic: /coupling_1502829dee/input
    joint_states_topic: /coupling_1502829dee/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_1502829dee_reach
    output_topic: /coupling_1502829dee/python/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
