/**:
  ros__parameters:
    chassis_base_frame: coupling_20cf85eb0d_base
    extension_metric: horizontal_reach
    input_topic: /coupling_20cf85eb0d/input
    joint_states_topic: /coupling_20cf85eb0d/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_20cf85eb0d_reach
    output_topic: /coupling_20cf85eb0d/cpp/output
    use_sim_time: false
