/**:
  ros__parameters:
    chassis_base_frame: coupling_de0464162e_base
    extension_metric: horizontal_reach
    input_topic: /coupling_de0464162e/input
    joint_states_topic: /coupling_de0464162e/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_de0464162e_reach
    output_topic: /coupling_de0464162e/python/output
    reach_full_m: 0.42
    scale_smoothing_alpha: 1.0
    use_sim_time: true
