
joint_limits:

  astribot_torso_joint_1:
    has_velocity_limits: true
    max_velocity: 6.0
    has_acceleration_limits: true
    max_acceleration: 17.1
  astribot_torso_joint_2:
    has_velocity_limits: true
    max_velocity: 6.0
    has_acceleration_limits: true
    max_acceleration: 17.1
  astribot_torso_joint_3:
    has_velocity_limits: true
    max_velocity: 6.0
    has_acceleration_limits: true
    max_acceleration: 17.1
  astribot_torso_joint_4:
    has_velocity_limits: true
    max_velocity: 6.0
    has_acceleration_limits: true
    max_acceleration: 17.1

  astribot_head_joint_1:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: true
    max_acceleration: 11.4
  astribot_head_joint_2:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: true
    max_acceleration: 11.4

  astribot_arm_left_joint_1:
    has_velocity_limits: true
    max_velocity: 8.4
    has_acceleration_limits: true
    max_acceleration: 24.0
  astribot_arm_left_joint_2:
    has_velocity_limits: true
    max_velocity: 8.4
    has_acceleration_limits: true
    max_acceleration: 24.0
  astribot_arm_left_joint_3:
    has_velocity_limits: true
    max_velocity: 8.4
    has_acceleration_limits: true
    max_acceleration: 24.0
  astribot_arm_left_joint_4:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: true
    max_acceleration: 42.9
  astribot_arm_left_joint_5:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: true
    max_acceleration: 42.9
  astribot_arm_left_joint_6:
    has_velocity_limits: true
    max_velocity: 16.8
    has_acceleration_limits: true
    max_acceleration: 48.0
  astribot_arm_left_joint_7:
    has_velocity_limits: true
    max_velocity: 16.8
    has_acceleration_limits: true
    max_acceleration: 48.0

  astribot_arm_right_joint_1:
    has_velocity_limits: true
    max_velocity: 8.4
    has_acceleration_limits: true
    max_acceleration: 24.0
  astribot_arm_right_joint_2:
    has_velocity_limits: true
    max_velocity: 8.4
    has_acceleration_limits: true
    max_acceleration: 24.0
  astribot_arm_right_joint_3:
    has_velocity_limits: true
    max_velocity: 8.4
    has_acceleration_limits: true
    max_acceleration: 24.0
  astribot_arm_right_joint_4:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: true
    max_acceleration: 42.9
  astribot_arm_right_joint_5:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: true
    max_acceleration: 42.9
  astribot_arm_right_joint_6:
    has_velocity_limits: true
    max_velocity: 16.8
    has_acceleration_limits: true
    max_acceleration: 48.0
  astribot_arm_right_joint_7:
    has_velocity_limits: true
    max_velocity: 16.8
    has_acceleration_limits: true
    max_acceleration: 48.0

  wheel_RF_Joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  wheel_LF_Joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  wheel_RR_Joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  wheel_LR_Joint:
    has_velocity_limits: false
    has_acceleration_limits: false

  astribot_gripper_left_joint_L1:
    has_velocity_limits: true
    max_velocity: 9.3
    has_acceleration_limits: true
    max_acceleration: 26.6
  astribot_gripper_right_joint_L1:
    has_velocity_limits: true
    max_velocity: 9.3
    has_acceleration_limits: true
    max_acceleration: 26.6
