
moveit_simple_controller_manager:

  controller_names:
    - arm_left_controller
    - arm_right_controller
    - torso_controller
    - gripper_left_controller
    - gripper_right_controller

  arm_left_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - astribot_arm_left_joint_1
      - astribot_arm_left_joint_2
      - astribot_arm_left_joint_3
      - astribot_arm_left_joint_4
      - astribot_arm_left_joint_5
      - astribot_arm_left_joint_6
      - astribot_arm_left_joint_7

  arm_right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - astribot_arm_right_joint_1
      - astribot_arm_right_joint_2
      - astribot_arm_right_joint_3
      - astribot_arm_right_joint_4
      - astribot_arm_right_joint_5
      - astribot_arm_right_joint_6
      - astribot_arm_right_joint_7

  torso_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - astribot_torso_joint_1
      - astribot_torso_joint_2
      - astribot_torso_joint_3
      - astribot_torso_joint_4

  gripper_left_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - astribot_gripper_left_joint_L1

  gripper_right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - astribot_gripper_right_joint_L1

trajectory_execution:
  allowed_execution_duration_scaling: 2.0
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.05

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
