
planner_configs:

  RRTstarConfig:
    type: geometric::RRTstar
    goal_bias: 0.05
    range: 0.0
    delay_collision_checking: true
    use_k_nearest: true
    rewire_factor: 1.1
    optimization_budget_sec: 0.5

  BITstarConfig:
    type: geometric::BITstar
    samples_per_batch: 100
    use_k_nearest: true
    use_graph_pruning: true
    prune_threshold_as_fractional_cost_change: 0.05
    delay_rewiring_to_first_solution: false
    use_just_in_time_sampling: false
    drop_unconnected_samples_on_prune: false
    stop_on_solution_improvement: false
    rewire_factor: 1.1

  InformedRRTstarConfig:
    type: geometric::InformedRRTstar
    goal_bias: 0.05
    range: 0.0
    delay_collision_checking: true
    rewire_factor: 1.1
    number_sampling_attempts: 100
    optimization_budget_sec: 0.5
    goal_state_wait_sec: 0.1

  RRTConnectConfig:
    type: geometric::RRTConnect
    range: 0.0

arm_left:
  default_planner_config: RRTstarConfig
  planner_configs:
    - RRTstarConfig
    - BITstarConfig
    - InformedRRTstarConfig
    - RRTConnectConfig
  projection_evaluator: joints(astribot_arm_left_joint_1,astribot_arm_left_joint_2)
  longest_valid_segment_fraction: 0.01

arm_right:
  default_planner_config: RRTstarConfig
  planner_configs:
    - RRTstarConfig
    - BITstarConfig
    - InformedRRTstarConfig
    - RRTConnectConfig
  projection_evaluator: joints(astribot_arm_right_joint_1,astribot_arm_right_joint_2)
  longest_valid_segment_fraction: 0.01

dual_arm:
  default_planner_config: BITstarConfig
  planner_configs:
    - RRTstarConfig
    - BITstarConfig
    - InformedRRTstarConfig
    - RRTConnectConfig
  projection_evaluator: joints(astribot_arm_left_joint_1,astribot_arm_right_joint_1)
  longest_valid_segment_fraction: 0.01

torso:
  default_planner_config: RRTstarConfig
  planner_configs:
    - RRTstarConfig
    - BITstarConfig
    - InformedRRTstarConfig
    - RRTConnectConfig
  projection_evaluator: joints(astribot_torso_joint_1,astribot_torso_joint_2)
  longest_valid_segment_fraction: 0.01

dual_arm_with_torso:
  default_planner_config: BITstarConfig
  planner_configs:
    - RRTstarConfig
    - BITstarConfig
    - InformedRRTstarConfig
    - RRTConnectConfig
  projection_evaluator: joints(astribot_torso_joint_1,astribot_torso_joint_2)
  longest_valid_segment_fraction: 0.01
