/**:
  ros__parameters:
    chassis_base_frame: coupling_d242ce6c7a_base
    extension_metric: horizontal_reach
    input_topic: /coupling_d242ce6c7a/input
    joint_states_topic: /coupling_d242ce6c7a/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_d242ce6c7a_reach
    output_topic: /coupling_d242ce6c7a/cpp/output
    reach_update_period_sec: 0.0
    scale_smoothing_alpha: 1.0
    use_sim_time: true
