/**:
  ros__parameters:
    chassis_base_frame: coupling_ae55d85e9f_base
    extension_metric: horizontal_reach
    input_topic: /coupling_ae55d85e9f/input
    joint_states_topic: /coupling_ae55d85e9f/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_ae55d85e9f_reach
    output_topic: /coupling_ae55d85e9f/cpp/output
    use_sim_time: false
