/**:
  ros__parameters:
    chassis_base_frame: coupling_01228a8c4e_base
    extension_metric: joint_deviation
    input_topic: /coupling_01228a8c4e/input
    joint_states_topic: /coupling_01228a8c4e/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_01228a8c4e_reach
    output_topic: /coupling_01228a8c4e/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
