/**:
  ros__parameters:
    chassis_base_frame: coupling_d20722fbe8_base
    extension_metric: horizontal_reach
    input_topic: /coupling_d20722fbe8/input
    joint_states_topic: /coupling_d20722fbe8/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_d20722fbe8_reach
    output_topic: /coupling_d20722fbe8/python/output
    reach_update_period_sec: 0.0
    scale_smoothing_alpha: 1.0
    use_sim_time: true
