/**:
  ros__parameters:
    chassis_base_frame: coupling_59819fff38_base
    extension_metric: joint_deviation
    input_topic: /coupling_59819fff38/input
    joint_states_topic: /coupling_59819fff38/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_59819fff38_reach
    output_topic: /coupling_59819fff38/python/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
