/**:
  ros__parameters:
    chassis_base_frame: coupling_0ed88c04d2_base
    extension_metric: joint_deviation
    input_topic: /coupling_0ed88c04d2/input
    joint_states_topic: /coupling_0ed88c04d2/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_0ed88c04d2_reach
    output_topic: /coupling_0ed88c04d2/python/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
