/**:
  ros__parameters:
    chassis_base_frame: coupling_6c16634833_base
    extension_metric: horizontal_reach
    input_topic: /coupling_6c16634833/input
    joint_states_topic: /coupling_6c16634833/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_6c16634833_reach
    output_topic: /coupling_6c16634833/python/output
    reach_update_period_sec: 0.0
    scale_smoothing_alpha: 1.0
    use_sim_time: true
