/**:
  ros__parameters:
    chassis_base_frame: coupling_c7c4f8152e_base
    extension_metric: joint_deviation
    input_topic: /coupling_c7c4f8152e/input
    joint_states_topic: /coupling_c7c4f8152e/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_c7c4f8152e_reach
    output_topic: /coupling_c7c4f8152e/python/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
