/**:
  ros__parameters:
    chassis_base_frame: coupling_ad5b88a968_base
    extension_metric: joint_deviation
    input_topic: /coupling_ad5b88a968/input
    joint_states_topic: /coupling_ad5b88a968/joints
    log_throttle_sec: 1000.0
    monitored_links:
    - coupling_ad5b88a968_reach
    output_topic: /coupling_ad5b88a968/cpp/output
    scale_smoothing_alpha: 1.0
    use_sim_time: true
